# Generated by Django 4.0.5 on 2022-06-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_dependent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='essn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
